[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
#opencv = "0.92.2"
image = "0.25.2"
rand = "0.9.0-alpha.2"

[dev-dependencies]
parameterized = "2.0.0"