[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
image = "0.25.2"
rand = "0.9.0-alpha.2"
rayon = "1.10.0"

[dev-dependencies]
assert_approx_eq = "1.0.0"